version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        # Freshness testing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        columns:
          - name: date_date
            description: date_of_purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: turnover from the specific product (= quantity * unit selling price)
          - name: quantity
            description: quantity sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: product of Greenweez
        columns:
           - name: products_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: purchase_price
             description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
           - name: orders_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: logcost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider